all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: localhost
          ansible_connection: local
    databases:
      hosts:
        db1:
          ansible_host: localhost
          ansible_connection: local
    app:
      hosts:
        app1:
          ansible_host: localhost
          ansible_connection: local
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3 